############ winter ############
# load files
wb <- read.csv("WinterBird.csv")	# bird data (including Japanese name)
wv <- read.csv("WinterVisit.csv")	# number of visits
wg <- read.csv("WinterGroup.csv")	# group identity

# data arrangement
Y <- wb[,4:12]	# excluding bird names & guilds
Y <- cbind(Y[,1],Y[,2],Y[,3],Y[,4],Y[,5],Y[,6],Y[,7],Y[,8],Y[,9])
S <- dim(Y)[1]	# number of observed species
V <- wv		# number of visits
V <- cbind(V[1,1],V[1,2],V[1,3],V[1,4],V[1,5],V[1,6],V[1,7],V[1,8],V[1,9])
V <- as.vector(V)
T <- length(wv)	# number of years
m <- 100		# number of augmented species
y <- matrix(0,ncol=T,nrow=m)
Y <- rbind(Y,y)	# zero-inflated matrix
G <- wg[,4]		# group identity of observed species
g <- rep(NA,length=m)
G <- c(G,g)
g <- length(table(G))	# number of groups
year <- 1:T
year <- (year-mean(year))/sd(year)	# standardization

# WinBUGS code
library(R2WinBUGS)
sink("model.txt")
cat("
    model{
    # prior distributions on community level estimates
    # mean value
    # parameter related to abundance
    mu.a0 ~ dnorm(0,0.001)	# intercept
    mu.a1 ~ dnorm(0,0.001)	# simple term
    mu.a2 ~ dnorm(0,0.001)	# quadratic term
    # parameter related to detectability
    mu.r0	~ dnorm(0,0.001)
    mu.r1 ~ dnorm(0,0.001)
    mu.r2 ~ dnorm(0,0.001)
    
    # standard deviation
    # parameter related to abundance
    sigma.a0 ~ dunif(0,10)	# intercept
    sigma.a1 ~ dunif(0,10)	# simple term
    sigma.a2 ~ dunif(0,10)	# quadratic term
    # parameter related to detectability
    sigma.r0 ~ dunif(0,10)
    sigma.r1 ~ dunif(0,10)
    sigma.r2 ~ dunif(0,10)
    # create precision
    tau.a0 <- pow(sigma.a0,-2)
    tau.a1 <- pow(sigma.a1,-2)
    tau.a2 <- pow(sigma.a2,-2)
    tau.r0 <- pow(sigma.r0,-2)
    tau.r1 <- pow(sigma.r1,-2)
    tau.r2 <- pow(sigma.r2,-2)
    
    psi ~ dunif(0,1)	# inclusion rate that generates wi
    
    # proportion of number of species among groups, which generated by uninformative Dirichlet prior
    for(i in 1:g){
    prop[i] ~ dgamma(1,1)
    prob[i] <- prop[i]/sum(prop[])
    }
    
    for(i in 1:(S+m)){
    # generating parameters of each species related to abundance
    a0[i] ~ dnorm(mu.a0,tau.a0)#I(-10,10)
    a1[i] ~ dnorm(mu.a1,tau.a1)#I(-10,10)
    a2[i] ~ dnorm(mu.a2,tau.a2)#I(-10,10)
    # generating parameters of each species related to detectability
    r0[i] ~ dnorm(mu.r0,tau.r0)#I(-10,10)
    r1[i] ~ dnorm(mu.r1,tau.r1)#I(-10,10)
    r2[i] ~ dnorm(mu.r2,tau.r2)#I(-10,10)
    # indicator variable whether each species is exposed to sampling or not
    w[i] ~ dbern(psi)
    # allocating unobserved species into one of the species groups
    G[i] ~ dcat(prob[1:g])
    
    # indicator variables indexing groups to which species belong
    G1[i] <- equals(G[i],1)		# 1 if species = group 1, otherwise 0
    G2[i] <- equals(G[i],2)		# 1 if species = group 2, otherwise 0
    G3[i] <- equals(G[i],3)		# 1 if species = group 3, otherwise 0
    G4[i] <- equals(G[i],4)		# 1 if species = group 4, otherwise 0
    G5[i] <- equals(G[i],5)		# 1 if species = group 5, otherwise 0
    G6[i] <- equals(G[i],6)		# 1 if species = group 6, otherwise 0
    G7[i] <- equals(G[i],7)		# 1 if species = group 7, otherwise 0
    
    for(j in 1:T){
    # ecological process model
    log(lambda[i,j]) <- a0[i] + a1[i]*year[j] + a2[i]*year[j]*year[j]	# equation (4)
    Z[i,j] ~ dpois(lambda[i,j])	# latent abundance of each species in each year
    A[i,j] <- Z[i,j]*w[i]		# latent abundance only for extant species
    o[i,j] <- step(A[i,j]-1)	# occupancy of each species in each year
    # detection process model
    r[i,j] <- 1/(1+exp(-(r0[i] + r1[i]*year[j] + r2[i]*year[j]*year[j])))	# equation (5)
    p[i,j] <- 1-pow(1-r[i,j],A[i,j])	# equation (1)
    Y[i,j] ~ dbin(p[i,j],V[j])	# detection procee in each year
    
    o1[i,j] <- o[i,j]*G1[i]		# occupancy of group 1
    o2[i,j] <- o[i,j]*G2[i]		# occupancy of group 2
    o3[i,j] <- o[i,j]*G3[i]		# occupancy of group 3
    o4[i,j] <- o[i,j]*G4[i]		# occupancy of group 4
    o5[i,j] <- o[i,j]*G5[i]		# occupancy of group 5
    o6[i,j] <- o[i,j]*G6[i]		# occupancy of group 6
    o7[i,j] <- o[i,j]*G7[i]		# occupancy of group 7
    
    A1[i,j] <- A[i,j]*G1[i]		# abundance of group 1
    A2[i,j] <- A[i,j]*G2[i]		# abundance of group 2
    A3[i,j] <- A[i,j]*G3[i]		# abundance of group 3
    A4[i,j] <- A[i,j]*G4[i]		# abundance of group 4
    A5[i,j] <- A[i,j]*G5[i]		# abundance of group 5
    A6[i,j] <- A[i,j]*G6[i]		# abundance of group 6
    A7[i,j] <- A[i,j]*G7[i]		# abundance of group 7
    
    }
    }
    
    ## counting species richness at each year
    for(j in 1:T){
    SR0[j]	<- sum(o[,j])	# whole species
    SR1[j]	<- sum(o1[,j])	# group 1
    SR2[j]	<- sum(o2[,j])	# group 2
    SR3[j]	<- sum(o3[,j])	# group 3
    SR4[j]	<- sum(o4[,j])	# group 4
    SR5[j]	<- sum(o5[,j])	# group 5
    SR6[j]	<- sum(o6[,j])	# group 6
    SR7[j]	<- sum(o7[,j])	# group 7
    
    ## counting abundance at each year
    AB0[j]	<- sum(A[,j])	# whole species
    AB1[j]	<- sum(A1[,j])	# group 1
    AB2[j]	<- sum(A2[,j])	# group 2
    AB3[j]	<- sum(A3[,j])	# group 3
    AB4[j]	<- sum(A4[,j])	# group 4
    AB5[j]	<- sum(A5[,j])	# group 5
    AB6[j]	<- sum(A6[,j])	# group 6
    AB7[j]	<- sum(A7[,j])	# group 7
    }
    
    ## estimating unknown number of distinct species that occupy any years
    R <- sum(w[1:(S+m)])
    
    }
    ",fill=TRUE)
sink()

##### run multi-species abundance model
# pass data into the model
data <- list("Y","S","V","T","m","G","g","year")
# initial values
inits <- function()list(mu.a0=rnorm(1),mu.a1=rnorm(1),mu.a2=rnorm(1),mu.r0=rnorm(1),mu.r1=rnorm(1),mu.r2=rnorm(1),
                        sigma.a0=runif(n=1,min=0.5,max=1),sigma.a1=runif(n=1,min=0.5,max=1),sigma.a2=runif(n=1,min=0.5,max=1),
                        sigma.r0=runif(n=1,min=0.5,max=1),sigma.r1=runif(n=1,min=0.5,max=1),sigma.r2=runif(n=1,min=0.5,max=1),
                        Z=1+matrix(rpois(n=(S+m)*T,lambda=0.25),ncol=T,nrow=(S+m)),
                        psi=runif(1),w=rbinom((S+m),1,0.5),
                        prop=runif(n=g,min=0,max=5))
# monitored parameters
# exclude some parameters because all parameters can not be passed into R
parameters <- c(
  "mu.a0","mu.a1","mu.a2","mu.r0","mu.r1","mu.r2",
  "sigma.a0","sigma.a1","sigma.a2","sigma.r0","sigma.r1","sigma.r2",
  "psi","prop","prob","w","G","R",
  "a0","a1","a2","r0","r1","r2",
  "SR0","SR1","SR2","SR3","SR4","SR5","SR6","SR7",
  "AB0","AB1","AB2","AB3","AB4","AB5","AB6","AB7",
  #	"A[1:S,]"
)
# conduct the analysis
out <- bugs(data,inits,parameters,"model.txt",
            n.chain=3,n.burnin=8000,n.iter=88000,n.thin=20,debug=TRUE,working.directory=getwd())
out

## save results as a csv-file
res <- as.data.frame(out[[10]])
write.table(res,"winter - abundance.csv",sep=",",append=F)


############ breeding season ############
# load files
bb <- read.csv("BreedBird.csv")	# bird data (including Japanese name)
bv <- read.csv("BreedVisit.csv")	# number of visits
bg <- read.csv("BreedGroup.csv")	# group identity

# data arrangement
Y <- bb[,4:12]	# excluding bird names & guilds
Y <- cbind(Y[,1],Y[,2],Y[,3],Y[,4],Y[,5],Y[,6],Y[,7],Y[,8],Y[,9])
S <- dim(Y)[1]	# number of observed species
V <- bv		# number of visits
V <- cbind(V[1,1],V[1,2],V[1,3],V[1,4],V[1,5],V[1,6],V[1,7],V[1,8],V[1,9])
V <- as.vector(V)
T <- length(bv)	# number of years
m <- 100		# number of augmented species
y <- matrix(0,ncol=T,nrow=m)
Y <- rbind(Y,y)	# zero-inflated matrix
G <- bg[,4]		# group identity of observed species
g <- rep(NA,length=m)
G <- c(G,g)
g <- length(table(G))	# number of groups
year <- 1:T
year <- (year-mean(year))/sd(year)	# standardization

##### run multi-species abundance model
# please input the same code as above described